### ISSUE TITLE
安装 OpenWrt的页面需要加一个二次确认

### ISSUE THREAD

**Issue by kissyouhunter** [ophub/luci-app-amlogic#1]
点完安装后最好加一个二次确认。
昨晚测试的时候一个手滑。。。

**Comment by ophub** [comment]
If the menu selection is wrong, do not restart, wait for the execution of the wrong option to complete, just select the correct installation again. The installation is a new partition write, you can continue to do the second operation.

Your suggestion is very good. I will study whether Luci allows interactive pop-up confirmation.

**Comment by kissyouhunter** [comment]
> If the menu selection is wrong, do not restart, wait for the execution of the wrong option to complete, just select the correct installation again. The installation is a new partition write, you can continue to do the second operation.
> 
> Your suggestion is very good. I will study whether Luci allows interactive pop-up confirmation.

dat would be great. a pop-up is needed for misclick.

**Comment by ophub** [comment]
I upgraded the plug-in just now and added the installation option confirmation in 1.8-7. Thank you for your suggestion.

**Comment by kissyouhunter** [comment]
> I upgraded the plug-in just now and added the installation option confirmation in 1.8-7. Thank you for your suggestion.

my pleasure

**Comment by f63531119** [comment]
感谢非常好用

**Comment by ophub** [comment]
Thank you, and please feel free to contact if you have any questions or suggestions.

**Comment by kissyouhunter** [comment]
> Thank you, and please feel free to contact if you have any questions or suggestions.

will do
