### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by binge8** [ophub/luci-app-amlogic#10]
目前在线升级好像只能设置从github的releases下载，希望开放从个人网盘或服务器下载，方便国内直连下载

**Comment by ophub** [comment]
编译openwrt的源码库和第三方插件都在github上，你可以实践一下，在国内编译openwrt时可能都拉取不了源代码。国内某个类似的网站，发布固件有存储空间的容量限制，使用限制，会员限制… 现在国内没有合适的编译和发布环境，可能在github上编译是目前唯一的选择，你的理想是我们一起的理想，新年伊始，愿我们都心想事成……



```
国内某同类网站的说明：
仓库容量 | Git 单仓库容量上限为 500M ，SVN 单仓库容量上限为 400M单文件最大 50M 用户总仓库容量为 5G 注：总仓库定义为用户名下以及所创建的组织下面的所有仓库。

附件容量 | 附件单文件大小上限为 100MB 单仓库附件总容量 1G
```

**Comment by binge8** [comment]
在github上编译是不错的选择，不过我编译完可以打包下载到我的自建小型服务器上，完全可以实现。看看这个 http://256pd.top:9666/

**Comment by ophub** [comment]
代码是开源的，完全开放，支持二次开发，你可以把下载的api处改一下，在你打包的openwrt里面集成自己修改的插件。除了wget下载文件的这个功能外，其他文面都可以通用

https://github.com/ophub/luci-app-amlogic/tree/main/luci-app-amlogic/root/usr/share/amlogic

就是这三个文件，分别下载固件，内核，插件

比如改这个地方，换成你指定的网站，文件的格式可以参考用github的文件，放你的网上，你平时更新这个文件的内容即可

https://github.com/ophub/luci-app-amlogic/blob/98c813b8c21bca84c2394f0abac9a87f7aa8d29b/luci-app-amlogic/root/usr/share/amlogic/amlogic_check_firmware.sh#L123

**Comment by binge8** [comment]
首先我是小白，再开发能力有限，再者，重复造轮子也没那个必要。只要在你的基础上，加个小功能，在设置界面能直接自己填写想要的下载链接，就完美了。当然，也许你有你的考虑，我只是个建议，祝新年快乐

**Comment by ophub** [comment]
你下载github的这个文件看一眼就明白了，可以什么都不改，只把api文件里面的内容改成你的文件的地址。这样你在插件里写自己的网站即可

https://api.github.com/repos/breakings/OpenWrt/releases

打开这个网址，复制，放你的网站上，内容改成你的固件地址。这是几十个tag的文件，删减下同类重复的无关的tag信息。脚本只读其中的几行，单节点信息也可以删减。你多看一眼就懂了。

删到剩一个tag节点，单节点里没有用到的信息也可删除，最后就剩下十行以內的一个文件了。你每次更新自己的这个文件即可

**Comment by binge8** [comment]
好的  明白  谢谢

**Comment by ophub** [comment]
```
    "node_id": "RE_kwDOFIyF_M4DI65_",
    "tag_name": "flippy_openwrt",
    "target_commitish": "main",
    "name": "v66",
    "draft": false,
    "prerelease": false,
    "created_at": "2021-11-03T03:02:57Z",
    "published_at": "2021-11-04T09:36:33Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/breakings/OpenWrt/releases/assets/48605524",
        "id": 48605524,
        "node_id": "RA_kwDOFIyF_M4C5alU",
        "name": "openwrt_h6_vplus_R21.11.11_k5.14.16-flippy-66+.7z",
        "label": null,
        "uploader": {
          "login": "breakings",
          "id": 25475074,
          "node_id": "MDQ6VXNlcjI1NDc1MDc0",
          "avatar_url": "https://avatars.githubusercontent.com/u/25475074?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/breakings",
          "html_url": "https://github.com/breakings",
          "followers_url": "https://api.github.com/users/breakings/followers",
          "following_url": "https://api.github.com/users/breakings/following{/other_user}",
          "gists_url": "https://api.github.com/users/breakings/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/breakings/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/breakings/subscriptions",
          "organizations_url": "https://api.github.com/users/breakings/orgs",
          "repos_url": "https://api.github.com/users/breakings/repos",
          "events_url": "https://api.github.com/users/breakings/events{/privacy}",
          "received_events_url": "https://api.github.com/users/breakings/received_events",
          "type": "User",
          "site_admin": false
        },
        "content_type": "application/x-7z-compressed",
        "state": "uploaded",
        "size": 338478639,
        "download_count": 12,
        "created_at": "2021-11-04T10:20:37Z",
        "updated_at": "2021-11-04T10:23:23Z",
        "browser_download_url": "https://github.com/breakings/OpenWrt/releases/download/flippy_openwrt/openwrt_h6_vplus_R21.11.11_k5.14.16-flippy-66%2B.7z"
      },
```

上面是一个节点的完整内容，改为只剩下面这几行即可。

```
    "tag_name": "flippy_openwrt",
    "assets": [
      {
        "created_at": "2021-11-04T10:20:37Z",
        "updated_at": "2021-11-04T10:23:23Z",
        "browser_download_url": "https://github.com/breakings/OpenWrt/releases/download/flippy_openwrt/openwrt_h6_vplus_R21.11.11_k5.14.16-flippy-66%2B.7z"
      },

```

代码的其他部分，在保证文件格式正确的情况下均可删除，插件下载固件就用到了这几行内容。

在内核和插件的下载中也是一样的方式，用github的文件，简化一下即可用。用到的节点内容在上面发给你的下载文件里面有，你在这三个api里面找到那几行保留即可。这样就形成了一个标准的接口文件。你更新自己的这几个文件即可。

你选择了把电视盒子当路由器用，就注定你是不平凡的人，折腾是你的乐趣，创新是你的品质，你都会解决的，只要你心中有梦，行动不止，你一定可以实现理想。

这个插件我是一边搜文档一边捏造出来的，从说明文档中可以看到，各项功能均以其他插件为原型进行改造。上传，版本查询，下载，安装，各种lua，javascript, css, shell，这都是我搜索现学的，之前不会，现在也仅限于用过的这一点功能，我还学会用photoshop做了一个logo，还用它的动画做了gif展示图，我连用ssh方式访问github进行文件管理都是半年前刚学会的，之前我一直在手机上用它的网页编辑文式编写代码。我想说的是，如果你想实现什么，不要说自己不会，也不要说别人做过了，也许你是最好的，无论他们觉得多么烂，但自己的成果就是此刻最好的状态，不是为了别人，是为了不辜负自己的创意，自己动手是件辛苦又幸福的事情。
