### ISSUE TITLE
用插件升级完整系统后，wan口无法拨号

### ISSUE THREAD

**Issue by hyusiter** [ophub/luci-app-amlogic#11]
主路由模式，用晶晨宝盒升级69+o-70+o，升级执行完毕，进入新的系统可见已经显示70+o了

但是无法拨号，在查错后，从“系统日志内”，得知无法自动创建`/dev/ppp`，依据错误日志提示的`mknod /dev/ppp c 108 0`创建后可正常拨号了，但是客户端无法上网，只能有op上ping百度可通，换到客户端依旧不行。然后我用u盘重新刷了新的系统后可以正常使用。

不知道提供这些内容是否可以判断问题，如果不行我可以继续补充“症状”。

期待大手子，帮我答疑，谢谢。

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/commit/9ac12af3ec4ab1dada1b6401b39863455e8a0808

转发一下f大的提示：
N1固件，从版本69开始， 把 mmcblk2p2、mmcblk2p3、mmcblk2p4的分区起始位置依次向后偏移了4MB,经测试已修复BTRFS csum failed BUG，此BUG会导致不能拨号，科学不正常，不能turbo acc加速等多种问题，必须按下列方法解决（2选1）
1. 由于分区布局发生了变化，必须通过U盘启动全新刷机才算是真正修复
2. 不想重刷的，在线升级后用df -h /查看所在的分区，如果在mmcblk2p2上的，需要再升级一次，保证rootfs在mmcblk2p3分区上才能避免 btrfs csum failed
