### ISSUE TITLE
Form Token Mismatch Issue

### ISSUE THREAD

**Issue by ketaksaan** [ophub/luci-app-amlogic#12]
![image](https://user-images.githubusercontent.com/97231188/159517458-2e895d22-d3d0-420f-bde2-01677626548a.png)
  
Do you know what is causing this problem to happen when I change the kernel? I think it is not from the file, because I did change the kernel with the same file but it works flawlessly.

**Comment by ophub** [comment]
Do other menus of this plugin work properly?
There is a dependency file in this manual upload. Did you add it when you customized the compilation?
https://github.com/ophub/luci-app-amlogic#depends

**Comment by ketaksaan** [comment]
I tried the other menus like Backup Firmware Settings and made the same problem. This fw made by someone in my forum and didn't include the luci-app-amlogic, so I run the onekey manual install. So is the command doesn't download all the dependency files? If it's not, how do I do it manual install properly?

**Comment by ophub** [comment]
Which is his upstream compiled source code? The 2 source code I've tested works fine:

https://github.com/openwrt/openwrt

https://github.com/coolsnowwolf/lede

**Comment by ketaksaan** [comment]
I think he's using the first source code because if I take a look a little bit, he is forking from your repo too.

**Comment by ophub** [comment]
![Snip20220324_2](https://user-images.githubusercontent.com/68696949/159823340-983befca-8cc7-49a9-ba94-39e72d69a54e.png)

![Snip20220324_4](https://user-images.githubusercontent.com/68696949/159823349-ac3e708c-4326-430a-b0de-9f1dfc079a03.png)

![Snip20220324_5](https://user-images.githubusercontent.com/68696949/159823350-28f44ff4-6516-462d-ace8-e21f59e9e47a.png)

![Snip20220324_6](https://user-images.githubusercontent.com/68696949/159823355-7ecd06b0-8f08-4ddd-8731-a14cb9be05f0.png)

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/2633962374091b9123cf485d602ecef90dcc8a2e/luci-app-amlogic/Makefile#L29-L31

I have tested 2 versions and they all work fine. The plug-in has dependent packages, if the current firmware is missing, it will not work properly.

**Comment by ophub** [comment]
If you are using the source code of the `18.06 branch`, the syntax is different. In [amlogic.lua](https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/luasrc/controller/amlogic.lua), `cbi` should use `form`

**Comment by ketaksaan** [comment]
![image](https://user-images.githubusercontent.com/97231188/159827556-3dfc421a-358a-423f-a5a7-4347c9529002.png)

as you can see, I already installed all the dependencies. 

![image](https://user-images.githubusercontent.com/97231188/159827996-fc084b18-3f8b-4719-bb39-6a406533917b.png)

If I take a wild guess, is this causing the problem? I already sync my date & time on luci, but the server log says it's 2021

**Comment by ketaksaan** [comment]
If you can't resolve my problem, it is totally okay. Though this is a modded firmware. I installed all the dependencies and still got the same error. I just want to change the kernel the easiest way by using your plugin.

**Comment by ophub** [comment]
What you see in the log window is the result of `uname -a`
You can manually upload the kernel to `/mnt/*4/`, then use the `openwrt-kernel` command to update the kernel

**Comment by ketaksaan** [comment]
I did change the kernel using command and it works. Although the previous problem still exists, I ran into another error and it looks like the BOOT partition is very small. Do you know the command to expand the BOOT partition? I knew this problem because I compared the modded fw with the one that works well when changing the kernel through luci.

**Comment by ophub** [comment]
Boot is enough, he will always be this big and will not increase

**Comment by ketaksaan** [comment]
Alright then, thank you so much for helping me until this far. Have a great rest of your day.
