### ISSUE TITLE
求助：L大的5.15版本无法编译此软件

### ISSUE THREAD

**Issue by annce** [ophub/luci-app-amlogic#13]
求助：L大的5.15版本无法编译此软件
怎么也编不进去，直接安装，提示成功，但是系统里找不到，重启也没用

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/main/README.cn.md#依赖

提示：当使用 [coolsnowwolf/lean](https://github.com/coolsnowwolf/luci/tree/master/libs/luci-lib-fs) 的源码库进行 OpenWrt 编译时，无须单独添加此依赖。当使用 [openwrt/openwrt](https://github.com/openwrt/openwrt/) 或其他源码库时请自行检查是否缺少 feeds/luci/libs/luci-lib-fs 依赖。添加方法如下：

```
# 添加 luci-lib-fs
svn co https://github.com/ophub/luci-app-amlogic/trunk/depends/luci-lib-fs feeds/luci/libs/luci-lib-fs
```

**Comment by ophub** [comment]
依赖现在已经移除了，可以直接编译了。
