### ISSUE TITLE
在线升级地址添加部分通配符支持？

### ISSUE THREAD

**Issue by GWan1234** [ophub/luci-app-amlogic#14]
很棒的项目，升级安装很方便，在使用中有一个需求：

使用action生成镜像到release，我编译了三种镜像，双L大和天灵的，我拒绝了生成多个tag和多个release，把它们合并到同一个release，

但是在宝盒里面升级就一直提示失败，release链接 [链接](https://github.com/Tao173/Auto-Update-Router/releases/tag/untagged-4fe9054e08e210242e60)
还请帮忙看看。

![image](https://user-images.githubusercontent.com/64321391/170930211-e641ea6a-3906-404c-a145-95d236c51d9f.png)

**Comment by ophub** [comment]
仓库的releases地址发一下，插件里的设置截图发一下。/etc/config/amlogic 文件发一下，配置填写对了就可以使用。

https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/etc/config/amlogic

你参照这插件设置里的说明，和仓库首页里的说明，把仓库地址，关键字，等几个值根据你的仓库实际情况填写对


https://github.com/ophub/luci-app-amlogic/blob/50b74176dd7f079986cc1a1d2de3fc148062aa52/luci-app-amlogic/root/usr/share/amlogic/amlogic_check_firmware.sh#L132

插件就是通过这几个关键字模糊匹配查找对应的固件

**Comment by GWan1234** [comment]
好的，我发现问题了，为了release置顶，我开了Draft上传，搞的地址一直在变。谢谢回复。

**Comment by GWan1234** [comment]
> SOC

我是个zz，我重新发布了release，现在可以检测到更新了，但是我不知道它匹配的哪一个版本固件，因为三个版本的固件我都放在一个里面，详见release，还麻烦你帮忙看看。
[链接链接链接防失效](https://github.com/Tao173/Auto-Update-Router/releases/tag/ARMv8_Plus_Myself)

**Comment by ophub** [comment]
下载最新的（最后上传到releases里面的，时间最新的）

```
# 下面这几个参数的赋值，就是插件设置里你填写的几项内容（其中的soc是插件自动根据当前固件识别，不用填）
firmware_repo="Tao173/Auto-Update-Router"
releases_tag_keywords="ARMv8_Plus_Myself"
soc="s905x3"
main_line_version="5.15"
firmware_suffix=".img.gz"

# 下面这个就是插件里查询最新固件的语句
curl -i -s "https://api.github.com/repos/${firmware_repo}/releases" | grep "browser_download_url" | grep -o "https:.*${releases_tag_keywords}.*_${soc}_.*${main_line_version}.*${firmware_suffix}" | sort -r | head -n 1

# 你把上面的2部分都依次执行下，得到结果是（最新发布的，时间戳在releases里是最新的）：
https://github.com/Tao173/Auto-Update-Router/releases/download/ARMv8_Plus_Myself/Lienol_s905x3_multi_21.02_k5.15.43-Shmily.img.gz
```

你吧3个大佬的源码编译的固件放一个tags里，只能有1个是被使用的。一般建议分成3个releases，在tag里给他们区分，这样在设置关键字的时候大家选不同人的源码编译的固件。比如tags里分别带Lienol、immortalwrt、Lean字样。

**Comment by GWan1234** [comment]
ok，谢谢解答🤝
