### ISSUE TITLE
更新3.1.104后 设备无法识别 显示为空

### ISSUE THREAD

**Issue by etnperlong** [ophub/luci-app-amlogic#16]
上一版本为 3.1.63 识别正常
设备： Phicomm N1

更新后显示如下
![image](https://user-images.githubusercontent.com/4851274/174988560-bbfe04bd-b063-406c-b48f-35b13796981d.png)
更新系统会显示
The custom firmware soc is invalid.

麻烦大佬有空的时候修复一下 谢谢

**Comment by etnperlong** [comment]
不好意思修正一下 上一版本是 3.1.63
回退之后识别正常

![image](https://user-images.githubusercontent.com/4851274/174990775-e3d84019-5a68-4d63-aa43-ba1a7722e063.png)

![image](https://user-images.githubusercontent.com/4851274/174990829-740e761f-90c9-4d14-89ae-461126ba4899.png)

**Comment by ophub** [comment]
半年前发布的固件，这个文件：
/etc/flippy-openwrt-release

缺一个值，你手动加一行即可，内容：
PLATFORM=amlogic

过年以后发布的固件都有这个值了。
