### ISSUE TITLE
need help on kernel auto update

### ISSUE THREAD

**Issue by naveen1hot** [ophub/luci-app-amlogic#17]
hi @ophub thanks for effort on this.
i need help on kernel auto update.
here is my config
![image](https://user-images.githubusercontent.com/67212860/178895209-bcf35346-8fef-4ccb-86f7-224c71b27551.png)
my actual kernel is 
![image](https://user-images.githubusercontent.com/67212860/178895315-41d75a0c-de19-443e-a4ba-4a4f66b459ba.png)
 so im trying to update 5.10.230.
while i click update kernel showing as 
![image](https://user-images.githubusercontent.com/67212860/178895514-4a04bdbb-b91c-409a-9a17-aaca1e0d5c30.png)

Kinldly help me where/what i am missing

**Comment by ophub** [comment]
Hi, Your TP-LINK is not supported.
this plugin only supports Amlogic s9xxx, Allwinner (V-Plus Cloud), and Rockchip (BeikeYun, Chainedbox L1 Pro) boxes.

The list of supported boxes is as follows:
https://github.com/ophub/amlogic-s9xxx-openwrt
