### ISSUE TITLE
 /etc/flippy-openwrt-release file is missing!

### ISSUE THREAD

**Issue by bzzjh** [ophub/luci-app-amlogic#21]
提示：etc/flippy-openwrt-release file is missing![](url)

**Comment by bzzjh** [comment]
![image](https://user-images.githubusercontent.com/59792849/200105140-c057ecf8-0049-4a65-8457-b6a9e7996452.png)

**Comment by bzzjh** [comment]
请问这是什么问题呢？

**Comment by bzzjh** [comment]
![image](https://user-images.githubusercontent.com/59792849/200105166-191dc4bb-f4c7-4bca-9238-99b9d3f07d0e.png)

**Comment by ophub** [comment]
你的版本实在太老了，手动添加这个文件。在ttyd里先执行下面这条命令。在更新即可。

`echo "PLATFORM='amlogic'" >/etc/flippy-openwrt-release`
