### ISSUE TITLE
无法上传升级

### ISSUE THREAD

**Issue by Beaverfffan** [ophub/luci-app-amlogic#22]
qemu h68k openwrt官方源5.15内核+6.0.8打包
手动上传固件显示

表单令牌不匹配

提交的安全令牌无效或已过期！

为了防止未经授权访问系统，您的请求已被阻止。点击下面的 “继续 »” 来返回上一页。

**Comment by ophub** [comment]
截图，什么地方

**Comment by Beaverfffan** [comment]
![X{NNSBK~ 0{G~{( J`5KEWV](https://user-images.githubusercontent.com/58569969/202601795-5fc7adae-1e03-4b2b-a918-8f581c54499d.png)

**Comment by ophub** [comment]
我测试正常，你是登录时间长了吧？重启试试。

![Snip20221118_4](https://user-images.githubusercontent.com/68696949/202609546-02028f91-4870-4a2f-a491-b7aaa578e99b.png)

![Snip20221118_5](https://user-images.githubusercontent.com/68696949/202609568-3a882866-4221-4a95-8200-faa6ebca189d.png)
