### ISSUE TITLE
manual upload update: form token mismatch

### ISSUE THREAD

**Issue by leakssh** [ophub/luci-app-amlogic#23]
`The submitted security token is invalid or already expired!`

In order to prevent unauthorized access to the system, your request has been blocked. Click "Continue »" below to return to the previous page.
![Screenshot_2022-11-21-14-50-54-867_com android chrome](https://user-images.githubusercontent.com/87708571/202994491-9d6dcaf2-a43a-461f-ae6e-87e01b7671a8.jpg)

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/203005408-8b3c9afd-4cb4-4bfa-b357-6c67900a71ef.png)

`Which repository's source code` is your openwrt compiled with? I use https://github.com/openwrt/openwrt and https://github.com/coolsnowwolf/lede test is fine.

**Comment by leakssh** [comment]
i am using the repository from here https://github.com/immortalwrt/immortalwrt does it have any effect? 
I try to check all depends are available correctly

**Comment by leakssh** [comment]
> ![image](https://user-images.githubusercontent.com/68696949/203005408-8b3c9afd-4cb4-4bfa-b357-6c67900a71ef.png)
> 
> `Which repository's source code` is your openwrt compiled with? I use https://github.com/openwrt/openwrt and https://github.com/coolsnowwolf/lede test is fine.

try to upload only the kernel not the full firmware, is it still normal?

**Comment by ophub** [comment]
![Snip20221121_1](https://user-images.githubusercontent.com/68696949/203047521-92be442f-d570-46f7-b737-ecf1f53d6103.png)

**Comment by ophub** [comment]
/mnt/*4

**Comment by leakssh** [comment]
> /mnt/*4
> 
> Is your openwrt system running on usb? Or is it written into emmc?

I run it on emmc, maybe something is wrong with this...
System Log:
`Mon Nov 21 22:03:29 2022 daemon.err uhttpd[5042]: Model amlogic/amlogic_info returns SimpleForm but is dispatched via cbi(),
Mon Nov 21 22:03:29 2022 daemon.err uhttpd[5042]: please change admin/system/amlogic to use the form() action instead.
Mon Nov 21 22:03:33 2022 daemon.err uhttpd[5042]: Model amlogic/amlogic_upload returns SimpleForm but is dispatched via cbi(),
Mon Nov 21 22:03:33 2022 daemon.err uhttpd[5042]: please change admin/system/amlogic/upload to use the form() action instead.
Mon Nov 21 22:03:33 2022 daemon.err uhttpd[5042]: Model amlogic/amlogic_upload returns SimpleForm but is dispatched via cbi(),
Mon Nov 21 22:03:33 2022 daemon.err uhttpd[5042]: please change admin/system/amlogic/upload to use the form() action instead.`

**Comment by ophub** [comment]
It seems that immortalwrt has different syntax requirements. I have time to compile a system and debug it.
