### ISSUE TITLE
The fdisk partition fails, Please try again

### ISSUE THREAD

**Issue by leakssh** [ophub/luci-app-amlogic#24]
every time you install to emmc for the first time, a warning like this will appear:
`The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or partx(8).`

`The fdisk partition fails, Please try again.`

after trying the second time it just worked. what's wrong with this? and this always happens when you want to install to emmc you have to do it twice and try to succeed

**Comment by ophub** [comment]
`cat /etc/flippy-openwrt-release`
What device, what soc, take a screenshot and post your error

**Comment by leakssh** [comment]
`$ cat /etc/flippy-openwrt-release`
```
PLATFORM='amlogic'
FAMILY='meson-gxl'
BOARD='s905x'
KERNEL_VERSION='5.15.79'
K510='0'
FDTFILE='meson-gxl-s905x-p212.dtb'
UBOOT_OVERLOAD='u-boot-p212.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT=''
SOC='s905x'
```

**Comment by ophub** [comment]
What box, error screenshot during operation
