### ISSUE TITLE
请问怎么在github actions编译的时候自定义固件源地址呢？

### ISSUE THREAD

**Issue by cjlhll** [ophub/luci-app-amlogic#25]
我照如下改了。没生效啊。files/etc/config/amlogic文件
```
config amlogic 'config'
	option enable '1'
	option amlogic_firmware_suffix '.img.gz'
	option amlogic_firmware_config '1'
	option amlogic_write_bootloader '1'
	option amlogic_firmware_repo 'https://github.com/cjlhll/N1-OpenWrt'
	option amlogic_kernel_branch '5.15'
	option amlogic_kernel_path 'https://github.com/breakings/OpenWrt/tree/main/opt/kernel'
	option amlogic_firmware_tag 'openwrt'
```

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic#custom-config

在你的diy2.sh里添加修改代码。

**Comment by cjlhll** [comment]
> https://github.com/ophub/luci-app-amlogic#custom-config
> 
> 在你的diy2.sh里添加修改代码。

就不需要这个amlogic文件了是吗？只用在diy2.sh里添加这部分代码就行了。

**Comment by ophub** [comment]
https://github.com/cjlhll/N1-OpenWrt/blob/master/.github/workflows/build-openwrt-N1.yml

```
    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
```

你看你现在的流程，先把files拷贝进去了，但是最后一行被DIY_P2_SH脚本svn又覆盖成luci-app-amlogic的原版config了。
所以你拷贝的files无效。
所以根据你的流程代码，只有在DIY_P2_SH里处理才是有效的。

**Comment by cjlhll** [comment]
> https://github.com/cjlhll/N1-OpenWrt/blob/master/.github/workflows/build-openwrt-N1.yml
> 
> ```
>     - name: Load custom configuration
>       run: |
>         [ -e files ] && mv files openwrt/files
>         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
>         chmod +x $DIY_P2_SH
>         cd openwrt
>         $GITHUB_WORKSPACE/$DIY_P2_SH
> ```
> 
> 你看你现在的流程，先把files拷贝进去了，但是最后一行被DIY_P2_SH脚本svn又覆盖成luci-app-amlogic的原版config了。 所以你拷贝的files无效。 所以根据你的流程代码，只有在DIY_P2_SH里处理才是有效的。

明白了。那我把这个文件删掉，在diy2.sh里配置一下。
是这样配置吗？
![image](https://user-images.githubusercontent.com/26736892/206627987-d28d00f7-9d9a-4be2-9ad9-2b661d32749b.png)

**Comment by ophub** [comment]
第一个网址对就可以，写你的仓库。
第二个是release里tags的关键字，只要保障你的tags里包含这个词就可以，而且其他x86等固件里不要包含这个词就可以。
第三个没变化可以不替换。

看你现在的仓库，这样写没问题，如果将来可能一个仓库打包x86等各种设备的固件，注意区分这个tags关键词

**Comment by cjlhll** [comment]
![image](https://user-images.githubusercontent.com/26736892/206628390-59c87c99-80ba-4cbc-b464-563193d7669d.png)
就是这个关键词是吗？我这样是没问题的呗？

**Comment by ophub** [comment]
对

**Comment by cjlhll** [comment]
> 对

收到。非常感谢。~

**Comment by ophub** [comment]
比如有的人，一个仓库打包x86的时候他的tags里叫openwrt_x86-64_xxxx
打包N1也叫openwrt_xxx就不行了，这个openwrt关键词无法锁定是N1，这时要给N1起个和其他架构不重复的，比如叫
openwrt_s9xxx_xxx （关键词是s9xxx）  或者  openwrt_N1_xxx (关键词是N1)
必须确保用的这个关键词能定位到这个下载列表里。和其他x86等架构的固件不重叠

**Comment by cjlhll** [comment]
> 比如有的人，一个仓库打包x86的时候他的tags里叫openwrt_x86-64_xxxx 打包N1也叫openwrt_xxx就不行了，这个openwrt关键词无法锁定是N1，这时要给N1起个和其他架构不重复的，比如叫 openwrt_s9xxx_xxx （关键词是s9xxx） 或者 openwrt_N1_xxx (关键词是N1)

我明白了。得是唯一关键词。非常感谢作者大大的及时回答。

**Comment by ophub** [comment]
不客气

**Comment by cjlhll** [comment]
> 不客气

你好，地址是改过来了，但是为什么检测到的升级不对劲呢，不是我的仓库的更新，时间对不上，我尝试更新后就打不开了。整个op的后台管理页面都报错了。忘了截图了。

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/9cd50cf99e10f77b69808befae8d73dc9a6a3aae/luci-app-amlogic/root/usr/share/amlogic/amlogic_check_firmware.sh#L141

**Comment by ophub** [comment]
curl -s "https://api.github.com/repos/你的用户/仓库地址/releases"

你看一下返回来的结果就知道了。
github的api使用美国时区（我没找到可以改时区的方法），所以返回的时候差8个时区。不是北京时间，但宝盒查询找出的肯定是最新的。结果正确。

目前支持使用这两个仓库的源码编译的tab包，其他仓库的源码可能不行，没适配过。
[OpenWrt](https://github.com/openwrt/openwrt)
[coolsnowwolf/lede](https://github.com/coolsnowwolf/lede)

**Comment by cjlhll** [comment]
![微信截图_20221213203812](https://user-images.githubusercontent.com/26736892/207320541-cfcbbd39-f083-4aa8-9b9f-6cb81a8a6ff6.png)
![微信截图_20221213203743](https://user-images.githubusercontent.com/26736892/207320555-91cd23ea-5a76-4e49-a08e-8815d9c01cad.png)
我怎么避免检查到此更新呢。

**Comment by cjlhll** [comment]
> ![微信截图_20221213203812](https://user-images.githubusercontent.com/26736892/207320541-cfcbbd39-f083-4aa8-9b9f-6cb81a8a6ff6.png) ![微信截图_20221213203743](https://user-images.githubusercontent.com/26736892/207320555-91cd23ea-5a76-4e49-a08e-8815d9c01cad.png) 我怎么避免检查到此更新呢。

确实是相差8小时

**Comment by ophub** [comment]
上面的在工作流yml里可以设置时区，下面api的不知道怎么设置。
但是这不影响查询最新固件的结果。

**Comment by cjlhll** [comment]
> 上面的在工作流yml里可以设置时区，下面api的不知道怎么设置。 但是这不影响查询最新固件的结果。

那就奇怪了。我特意把release删空了。然后重新编译了一次。刷入后还是能检测到更新。刚开始检测不到，过8小时就能检测到了。

**Comment by ophub** [comment]
删tags

**Comment by cjlhll** [comment]
> 删tags

删完了。release和tags都删干净了。测试的。
