### ISSUE TITLE
r66s用immortalwrt固件识别不到设备

### ISSUE THREAD

**Issue by vxbmtu94516** [ophub/luci-app-amlogic#26]
![image](https://user-images.githubusercontent.com/89058555/207017194-73d05068-64aa-4d82-b817-08fe6f95d189.png)

**Comment by ophub** [comment]
这个没适配。这个源码的语法不一样。你在哪下的固件呢？发个编好的链接我调试一下。

**Comment by vxbmtu94516** [comment]
用的是snapshots版
要手动装luci
https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/immortalwrt-rockchip-armv8-lunzn_fastrhino-r66s-squashfs-sysupgrade.img.gz

**Comment by ophub** [comment]
f大打包的op固件里有一个版本信息文件：/etc/flippy-openwrt-release

这个固件里没有，所以有些功能会版本识别不正确。另外我也不了解，这个固件如果使用晶晨宝盒的更新固件、更新内核这些是否可以，我没安装，但是我猜这个应该不是4个分区设置。所以大概率来看，可能不适合使用宝盒升级更新。

但是如果使用的不是这个成品固件，而是用tar包打包，就可以。这种方式的可以适配（目前没适配，之前有人反应过接口不同）

**Comment by vxbmtu94516** [comment]
我用f大的打包脚本加上[default-rootfs.tar.gz](https://downloads.immortalwrt.org/snapshots/targets/armvirt/64/immortalwrt-armvirt-64-default-rootfs.tar.gz)打包出来的好像直接开不起来

**Comment by vxbmtu94516** [comment]
我最开始是用本地打包脚本做的 开不起机来就想着装宝盒用宝盒去更新内核
现在看来还是得专门适配过的固件才行

**Comment by ophub** [comment]
[OpenWrt](https://github.com/openwrt/openwrt)
[coolsnowwolf/lede](https://github.com/coolsnowwolf/lede)

目前只适配了这两个，其他的没调试过。
