### ISSUE TITLE
系统升级很好用，能不能支持对X86CPU的支持？

### ISSUE THREAD

**Issue by vpei** [ophub/luci-app-amlogic#30]
系统升级很好用，能不能支持对X86CPU的支持？

**Comment by ophub** [comment]
这个插件是对f大开发的openwrt的定制化支持。

x86有openwrt系统默认自带的升级工具，在系统菜单底下----升级---上传对应格式的固件在线更新即可。

**Comment by vpei** [comment]
还是你的这个升级好用，那个自带的升级不大靠谱，自己添加的分区，经常给搞没了。docker安装的软件在那个自定义分区上，只要升级了，就需要把所有软件都重装一遍。
