### ISSUE TITLE
大佬，能不能加入自定义备份文件和文件夹的选项？

### ISSUE THREAD

**Issue by xuexiao-weizi** [ophub/luci-app-amlogic#34]
大佬，能不能加入自定义备份文件和文件夹的选项？

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/usr/sbin/openwrt-backup

这个里面

**Comment by xuexiao-weizi** [comment]
> https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/usr/sbin/openwrt-backup
> 
> 这个里面



> https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/usr/sbin/openwrt-backup
> 
> 这个里面

好的，谢谢了！研究研究！
