### ISSUE TITLE
贝壳云刷了haiibo/OpenWrt为什么无法升级

### ISSUE THREAD

**Issue by tedcriss** [ophub/luci-app-amlogic#37]
贝壳云刷了[haiibo/OpenWrt](https://github.com/haiibo/OpenWrt)，使用晶晨宝盒本地升级，上传了解压后的img文件，点击升级后提示```mount /dev/loop0p2 -> /mnt/mmcblk0p4/root ... mount failed```，ssh检查```/dev```发现无```/dev/loop0p2```目录，这是咋回事哇？

**Comment by tedcriss** [comment]
现有固件版本为```OpenWrt R23.04.20 by Haiibo / LuCI Master (git-23.109.50273-11b9572)```，内核版本为```6.1.24-flippy-82+```。

**Comment by tedcriss** [comment]
另外，在我家云上也遇到了一致的问题。固件版本```OpenWrt R22.12.13 (2022-12-13 21:13:25 by flippy) / LuCI Master (git-22.339.26541-ba1f838)```，内核版本```6.0.12-flippy-79+```。

**Comment by ophub** [comment]
上传压缩包，不要上传解压的img，会因为不完整失败。
p4分区剩余可用空间要大于2G

**Comment by tedcriss** [comment]
上传了原始下载的img.gz文件，点击更新，在提示```Update using [ openwrt_rk3328_beikeyun_R23.4.1_k6.1.28-flippy-83+.img.gz ] file. Please wait a moment ...```后更新失败，提示```No update file found.```。

**Comment by ophub** [comment]
把p4里面之前上传的不完整文件都删了。重传完整。
先把插件升级到最新版。

**Comment by tedcriss** [comment]
成功了，网页上传怎么都不会完整，一定要用ssh后台传上去才可以，要传img.gz格式，传到p4目录下就自动识别到了，更新一次成功。
