### ISSUE TITLE
在线更新内核出错 [[1;91m Error [0m] The [ boot ] file is missing.

### ISSUE THREAD

**Issue by woboo110** [ophub/luci-app-amlogic#38]
日志如下
![image](https://github.com/ophub/luci-app-amlogic/assets/68997087/a6308fa6-f076-4090-89bb-02d4333bb0f0)

**Comment by ophub** [comment]
宝盒插件---手动上传更新----列表看到的文件都删除干净。
在线下载更新----仅更新内核----更新

**Comment by woboo110** [comment]
> 宝盒插件---手动上传更新----列表看到的文件都删除干净。 在线下载更新----仅更新内核----更新

里面没有文件。。。
