### ISSUE TITLE
在晶晨宝盒里安装openwrt到emmc错误

### ISSUE THREAD

**Issue by lpfxh** [ophub/luci-app-amlogic#39]
是S905L3Acpu M401A型号，固件支持u盘启动openwrt，在u盘系统下安装openwrt到emmc提示分区错误。是因为安卓包底层有问题吗

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.16
