### ISSUE TITLE
这两个总是失败呢

### ISSUE THREAD

**Issue by rq1025330** [ophub/luci-app-amlogic#4]
![image](https://user-images.githubusercontent.com/52870887/127091945-6fab212c-af5a-41c9-8a6b-16d88c9811cd.png)

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/127092598-e061c2b9-c2c3-4633-be02-2e8ca246cb49.png)

**Comment by ophub** [comment]
`curl -fsSL git.io/luci-app-amlogic | bash`

Ensure that openwrt can only be updated when the network can access github.com normally.

Reinstall, take a screenshot to see the plug-in settings interface

**Comment by rq1025330** [comment]
更新后可以l

**Comment by rq1025330** [comment]
昨天测试更新内核依然不行 ，更新插件、镜像包都可以。网络确定没得问题。
