### ISSUE TITLE
大佬，能造福一下x86的用户吗？在X86提供一下像晶晨宝盒这样的升级，谢谢了！！！

### ISSUE THREAD

**Issue by xuexiao-weizi** [ophub/luci-app-amlogic#40]
大佬，能造福一下x86的用户吗？在X86提供一下像晶晨宝盒这样的升级，谢谢了！！！

**Comment by ophub** [comment]
x86有系统自带的升级工具，在系统菜单下

**Comment by xuexiao-weizi** [comment]
自带的不好用，如果把一块硬盘分多个区的话，用自带的升级会把分区抹去了，数据也没有了。还是和晶晨宝盒一样弄AB无损升级方便。
