### ISSUE TITLE
DG-3399晶晨宝盒显示设备型号为当前设备：PLATFORM: rockchip

### ISSUE THREAD

**Issue by LemonCrab666** [ophub/luci-app-amlogic#41]
DG-3399晶晨宝盒显示设备型号为当前设备：PLATFORM: rockchip，在线检查晶晨宝盒更新显示The search results for releases are empty.

**Comment by ophub** [comment]
插件设置里填写的什么，截图发下

**Comment by LemonCrab666** [comment]
![Uploading A645880E-6B1B-48A4-BB6F-1D31AE0F6E75.png…]()

**Comment by LemonCrab666** [comment]
![Uploading 09BE7383-C416-4CA4-B2FD-66ECDF8E706F.png…]()

**Comment by LemonCrab666** [comment]
![微信截图_20230717200501](https://github.com/ophub/luci-app-amlogic/assets/55867630/77973eb2-0524-49a4-aeff-c00fe792ca38)

**Comment by ophub** [comment]
在线下载更新，先点第一个按钮（升级插件），等执行完了，再点第三个按钮（更新完整固件）

**Comment by LemonCrab666** [comment]
> 在线下载更新，先点第一个按钮（升级插件），等执行完了，再点第三个按钮（更新完整固件）

我是自编译的，用你的打包出来的

**Comment by ophub** [comment]
你把设置里的固件地址改成你的仓库

**Comment by LemonCrab666** [comment]
直接选择本地img.gz文件提示Unknown device: [ DG-3399 ], Not supported.dtb用的也是仓库里提供的

**Comment by LemonCrab666** [comment]
> 你把设置里的固件地址改成你的仓库
直接选择本地img.gz文件提示Unknown device: [ DG-3399 ], Not supported.dtb用的也是仓库里提供的

**Comment by LemonCrab666** [comment]
> 你把设置里的固件地址改成你的仓库

直接选择本地img.gz文件提示Unknown device: [ DG-3399 ], Not supported.dtb用的也是仓库里提供的

**Comment by LemonCrab666** [comment]
> 你把设置里的固件地址改成你的仓库

![QQ截图20230917172652](https://github.com/ophub/luci-app-amlogic/assets/55867630/0dba3e73-dbea-4d7c-931d-46744d33ca7d)

文件大小也不对
