### ISSUE TITLE
N1手动更新固件或在线更新均失败

### ISSUE THREAD

**Issue by bosense** [ophub/luci-app-amlogic#42]
提示：2023-07-25 18:45:20 /etc/flippy-openwrt-release file is missing!是自己编译的插件，安装在原有的系统中

**Comment by ophub** [comment]
你编译的rootfs.tar.gz，使用f大的打包时会添加这个文件

**Comment by bosense** [comment]
当时打包好像用的不是f大的，那就只能重新打包了吗？
