### ISSUE TITLE
无法支持新版LuCI的上传功能

### ISSUE THREAD

**Issue by OldCoding** [ophub/luci-app-amlogic#44]
在immortalwrt中无法正常上传，使用的是master分支，回复的是“新 LuCI 已不支持传统 lua 插件的文件上传功能，重写为 js 即可。”，望更新一下以支持新版LuCI
![image](https://github.com/ophub/luci-app-amlogic/assets/85047508/268c8cca-0023-46de-94e9-2d7b72528bed)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_immortalwrt_save_2023.08

我下载测试了可以上传，你使用的什么版本。去看了下他luci仓库的文件上传是1年前更新的，还是lua，你能找个JavaScript上传的app案例发我个地址我学习学习。

https://github.com/immortalwrt/luci/tree/master/applications/luci-app-filetransfer

![Snip20230902_2](https://github.com/ophub/luci-app-amlogic/assets/68696949/614f98a4-b61c-4db6-8cea-a71a68eca434)

![Snip20230902_3](https://github.com/ophub/luci-app-amlogic/assets/68696949/b88ad91b-99bd-4432-bade-acdef07dd4e9)

![Snip20230902_4](https://github.com/ophub/luci-app-amlogic/assets/68696949/cb127d8d-caed-4802-82db-58ad2ad1d6ad)

**Comment by OldCoding** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_immortalwrt_save_2023.08
> 
> 我下载测试了可以上传，你使用的什么版本。去看了下他luci仓库的文件上传是1年前更新的，还是lua，你能找个JavaScript上传的app案例发我个地址我学习学习。
> 
> https://github.com/immortalwrt/luci/tree/master/applications/luci-app-filetransfer
> 
> ![Snip20230902_2](https://user-images.githubusercontent.com/68696949/265185217-614f98a4-b61c-4db6-8cea-a71a68eca434.png)
> 
> ![Snip20230902_3](https://user-images.githubusercontent.com/68696949/265185221-b88ad91b-99bd-4432-bade-acdef07dd4e9.png)
> 
> ![Snip20230902_4](https://user-images.githubusercontent.com/68696949/265185225-cb127d8d-caed-4802-82db-58ad2ad1d6ad.png)

我用的是自编译的固件，https://github.com/OldCoding/openwrt_packit_arm/releases/tag/ARMv8-im
案例我这就没有了，天灵说在软件包的页面可以直接上传APK，你可以看下是否能找到相关的功能源码

**Comment by Saxon-Sun** [comment]
@ophub 问下luci-app-amlogic支持openwrt luci 23.05分支的吗？

**Comment by ophub** [comment]
支持

**Comment by Saxon-Sun** [comment]
> 支持

谢谢大佬
