### ISSUE TITLE
DG-3399晶晨宝盒显示设备型号为当前设备：PLATFORM: rockchip

### ISSUE THREAD

**Issue by LemonCrab666** [ophub/luci-app-amlogic#45]
直接选择本地img.gz文件提示Unknown device: [ DG-3399 ], Not supported.
![QQ截图20230917172652](https://github.com/ophub/luci-app-amlogic/assets/55867630/23c07d8c-093a-4599-8023-93cf11042d40)
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/c3a41c13-647f-40b8-9db1-8d8c658c8dc3)
文件大小也不对

**Comment by ophub** [comment]
当前设备：rockchip 是对的，这个地方会显示设备的平台，支持的设备会显示为 amlogic/allwinner/rockchip 三个平台。


文件上传：你使用ssh访问，上传文件到/mnt/*p4/ 的目录下，然后在此可以看到p4里上传的文件，然后点击更新即可。

使用lede的源码编译的固件，上传基本上没问题。但是immortalwrt现在使用的JavaScript替代了lua，上传我发现不太好用了，需要改这个上传功能为JavaScript，我在纠结是以lede为主还是换。

**Comment by LemonCrab666** [comment]
> 当前设备：rockchip 是对的，这个地方会显示设备的平台，支持的设备会显示为 amlogic/allwinner/rockchip 三个平台。 文件在线上传不如ftp上传好。你使用ssh访问，上传文件到/mnt/*p4/ 的目录下，然后在此可以看到p4里上传的文件，然后点击更新即可。

我刚看了下[openwrt-update-rockchip](https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/usr/sbin/openwrt-update-rockchip)这个文件，里面是没有rk3399的分类和机型的，是因为这个原因没办法正确识别机型吗

**Comment by ophub** [comment]
那个地方识别的是平台PLATFORM，不是soc

**Comment by LemonCrab666** [comment]
> 使用lede的源码编译的固件，上传基本上没问题。但是immortalwrt现在使用的JavaScript替代了lua，上传我发现不太好用了，需要改这个上传功能为JavaScript，我在纠结是以lede为主还是换。

我刚直接winscp上传了img文件，显示依旧是Unknown device: [ dg3399 ], Not supported.
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/2fd5b4f2-2788-4e75-b21c-355dcfd55973)

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/547661e2dc3e50ea44b747057f5a70897bae7959/luci-app-amlogic/luasrc/model/cbi/amlogic/amlogic_config.lua#L24-L29

显示rockchip是对的。

**Comment by LemonCrab666** [comment]
> https://github.com/ophub/luci-app-amlogic/blob/547661e2dc3e50ea44b747057f5a70897bae7959/luci-app-amlogic/luasrc/model/cbi/amlogic/amlogic_config.lua#L24-L29
> 
> 显示rockchip是对的。

机型显示也无所谓了，现在就是手动更新一直不成功，打包用的amlogic-s9xxx-openwrt

**Comment by LemonCrab666** [comment]
> https://github.com/ophub/luci-app-amlogic/blob/547661e2dc3e50ea44b747057f5a70897bae7959/luci-app-amlogic/luasrc/model/cbi/amlogic/amlogic_config.lua#L24-L29
> 
> 显示rockchip是对的。

按照您说的办法也没解决，还有什么脚本可以直接更新吗

**Comment by ophub** [comment]
更新固件的脚本要升级一下，支持从记录文件里读取更多自定义的盒子。明天我抽空升级一下。

**Comment by LemonCrab666** [comment]
> 更新固件的脚本要升级一下，支持从记录文件里读取更多自定义的盒子。明天我抽空升级一下。

好的，明天我再试下

**Comment by ophub** [comment]
升级插件到198试试

**Comment by LemonCrab666** [comment]
> 升级插件到198试试

更新完，开不开机了……

**Comment by ophub** [comment]
我测试正常。拔插电源看看。提供有用的信息。

**Comment by LemonCrab666** [comment]
> 我测试正常。拔插电源看看。提供有用的信息。

重新插拔电源过了，设备灯正常亮，op没有启动，hdmi也没输出，刷写的时候勾选了bootloader，跟这个有关吗

**Comment by ophub** [comment]
那个选项只对amlogic有用

**Comment by LemonCrab666** [comment]
> 那个选项只对amlogic有用

我再不勾选试试看，选择安装包之后更新是正常的，一直到更新完成重启，可能是勾选这个选项导致没有引导开机吧，现在插上电源什么反应都没有，hdmi也没有输出

**Comment by ophub** [comment]
勾不勾对你无差别，只对amlogic有效，和勾无关。

**Comment by LemonCrab666** [comment]
> 勾不勾对你无差别，只对amlogic有效，和勾无关。

重新刷入之后，再次用198更新，出现图中提示
![A24742F4-C8C3-493F-98CE-F3C37099FF2D](https://github.com/ophub/luci-app-amlogic/assets/55867630/9c7c6b4d-ce7e-4c66-9766-c81aee699311)

**Comment by LemonCrab666** [comment]
> 勾不勾对你无差别，只对amlogic有效，和勾无关。

大佬，这个提示要怎么解决呢
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/4275d900-f7e6-4736-a05e-b6c7f97cfc99)

**Comment by ophub** [comment]
更新最新版插件，重启设备试试。

**Comment by LemonCrab666** [comment]
> 更新最新版插件，重启设备试试。

更新了最新的插件201，也重启了设备，更新依然提示这个
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/6103c305-331f-46ad-b1b3-55f4b2031727)

**Comment by LemonCrab666** [comment]
> 更新最新版插件，重启设备试试。

重新打包最新的内核，更新成功，但是重启设备hdmi无画面，可能无法引导系统

**Comment by ophub** [comment]
去路由器里看看armbian设备有没有上线，看看ip

**Comment by LemonCrab666** [comment]
> 去路由器里看看armbian设备有没有上线，看看ip

luci界面无法进入，也ping不到设备

**Comment by LemonCrab666** [comment]
> 去路由器里看看armbian设备有没有上线，看看ip

重刷了一遍，依然是这个问题，更新后无法开机，无HDMI显示无法ping到设备，路由器也看不到设备上线

**Comment by LemonCrab666** [comment]
仅更新内核也不成功
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/a06a1dbb-498a-4664-97c1-c8de4e310877)
![image](https://github.com/ophub/luci-app-amlogic/assets/55867630/063c118e-a8f4-4a42-b42c-503563615319)
版本分支设置的没问题

**Comment by ophub** [comment]
这个是无法查询服务器，先把op上网设置好了，让盒子可以正常访问github.com服务器。

**Comment by LemonCrab666** [comment]
> 这个是无法查询服务器，先把op上网设置好了，让盒子可以正常访问github.com服务器。

网络设置没有问题，github服务器可以正常访问
