### ISSUE TITLE
Mount p2 [ /dev/loop0p2 ] failed!

### ISSUE THREAD

**Issue by Cusox** [ophub/luci-app-amlogic#50]
![photo_2024-02-03_01-56-54](https://github.com/ophub/luci-app-amlogic/assets/43839502/ff51719b-78eb-4d22-8037-e04fb73f2989)
自己打包的固件，手动上传更新失败，粗略看了看好像是因为没有进行umount /dev/loop0p2，是缺少了什么必要依赖吗
看到了类似的issue #19 ，但尝试过重启和重新打包也是这样

**Comment by Leon19960120** [comment]
找到解决方案了吗

**Comment by Cusox** [comment]
> 找到解决方案了吗

网页上传的问题，上传的固件不是完整的，建议用 usb 手动挂载移动固件到指定目录
