### ISSUE TITLE
升级全固件后重启失败

### ISSUE THREAD

**Issue by binge8** [ophub/luci-app-amlogic#52]
lede仓库，升级过程成功了，最后一步重启就失败，必须手动拔电在插上就好了。s905x3，x96max+，bootloader和保留配置也勾选了，6.1.81内核

**Comment by ophub** [comment]
s905x3有reboot的无法启动的概率，虽然很少碰到，暂时无解，你的手动拔电重插是现在的解决方法。

**Comment by binge8** [comment]
有解了吗？我是远程升级，每次都失联，反正我这里不是概率的问题，是一直这样

> s905x3有reboot的无法启动的概率，虽然很少碰到，暂时无解，你的手动拔电重插是现在的解决方法。

**Comment by ophub** [comment]
你试一下不同系列的内核哪个可以启动，从5.4.y到6.6.y
