### ISSUE TITLE
使用 LuCI 界面更新固件及内核无法找到依赖，使用 openwrt-kernel 终端命令则正常

### ISSUE THREAD

**Issue by etnperlong** [ophub/luci-app-amlogic#54]
作者大大你好👋

我在尝试使用 LuCI 界面更新内核时，会出现以下错误 
` [Error] Missing [ tar ] in OpenWrt firmware, unable to update kernel`

![image](https://github.com/ophub/luci-app-amlogic/assets/4851274/fbb9dcbd-c040-44ec-9386-b081ff5b47e5)

但如果我在失败之后，通过SSH终端输入 `openwrt-kernel` 指令，则可成功更新内核

经过测试，我发现无论是更新系统还是更新内核，使用 LuCI 界面均会出现 找不到依赖 的错误，但使用相应的 SSH 命令则会成功

检查代码后发现相关行在 https://github.com/ophub/luci-app-amlogic/blob/bcaf9d5b4f7b55adbf5bf75dcefab028e06c31c3/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic#L122
和 https://github.com/ophub/luci-app-amlogic/blob/bcaf9d5b4f7b55adbf5bf75dcefab028e06c31c3/luci-app-amlogic/root/usr/sbin/openwrt-kernel#L59

我的设备是 N1 盒子，运行的系统是 ImmortalWRT 23.05.2， 使用 [amlogic-s9xxx-openwrt](https://github.com/ophub/amlogic-s9xxx-openwrt) 中 ImageBuilder 方式构建，加入自定义的软件包

系统信息如下：
[Powered by LuCI openwrt-23.05 branch (git-24.086.26304-1d8fc03)](https://github.com/openwrt/luci)
[ArgonTheme v2.3.1](https://github.com/jerrykuku/luci-theme-argon)
ImmortalWrt 23.05.2 r27625-416c8c5c91

晶晨宝盒版本： 3.1.234-1

不清楚是哪个环节导致 LuCI 界面的指令失效，希望作者如果有时间的话，帮我除错一下，谢谢🙏
如果需要更多的详细信息，我可以提供

**Comment by ophub** [comment]
把你使用ImageBuilder构建的openwrt下载地址发一下

**Comment by etnperlong** [comment]
> 把你使用ImageBuilder构建的openwrt下载地址发一下

好的，我是通过本地构建的，镜像已经通过 OneDrive 临时分享
[链接](https://makeppt-my.sharepoint.com/:u:/g/personal/pan_makeppt_onmicrosoft_com/EfCJ1nILFYNDp0wER_lYQ-IBa5aTE2vUD-d98rGyeoR1Mw?e=ORXLKe)
谢谢！

**Comment by ophub** [comment]
![Snip20240614_1](https://github.com/ophub/luci-app-amlogic/assets/68696949/5e191b7f-fff7-4cf8-aa81-f36516df14c8)
![Snip20240614_2](https://github.com/ophub/luci-app-amlogic/assets/68696949/9a571376-d3c0-4cf3-9395-468f8bd630c3)

你提供的下载链接不可以，我测试了我在线构建的可以。
https://github.com/ophub/amlogic-s9xxx-openwrt/releases

你参考下必备软件包，看看少了什么，看10.11
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/documents/README.cn.md

**Comment by etnperlong** [comment]
谢谢你的帮忙！我检查过了必备的软件包，发现缺少了 Python 的部分，但我通过 opkg 重新安装后，依然无法通过 Luci 界面更新

我检查了一下在线构建的源，发现源采用的是 master 分支从头编译，而我使用的构建方法则是 使用了 23.05 正式版的 Imagebuilder

通过修改 lua 脚本，我尝试使用 `env` 命令引出了通过 SSH 执行和 LuCI 界面执行的不同

SSH 执行的输出如下
```shell
SHELL=/bin/bash
ENV=/etc/shinit
PWD=/root
LOGNAME=root
HOME=/root
SSH_CONNECTION=192.168.0.2 65432 192.168.0.1 22
TERM=xterm-256color
USER=root
SHLVL=1
PS1=\[\e]0;\u@\h: \w\a\]\u@\h:\w\$ 
SSH_CLIENT=192.168.0.2 65432 22
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SSH_TTY=/dev/pts/0
_=/usr/bin/env
```

而通过 LuCI 界面执行 env，输出如下
```shell
PWD=/www
SHLVL=1
_=/usr/bin/env
```

两者的重要差别是，LuCI 执行命令时缺少了 PATH 环境变量

于是我在上方我提及的两个脚本的首行添加
```shell
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

再次使用 LuCI 界面操作，即可成功完成更新
![Amlogic mod success](https://github.com/ophub/luci-app-amlogic/assets/4851274/fefd4465-9067-4221-9dc9-bae5be08abe8)

**Comment by etnperlong** [comment]
不知道产生差异的原因会不会是 OpenWRT 或 ImmortalWRT 的 LuCI 对于 snapshot 和 正式版本的行为有差异，待我去检查一下他们的代码或查看其他软件包开发者的处理方法，再回来报告

**Comment by ophub** [comment]
感谢分享你的发现。

我去imm的luci仓库里搜索了一下，看看是不是有其他app也要显示声明path，但搜了一下没找到有声明的： https://github.com/search?q=repo%3Aimmortalwrt%2Fluci%20export%20PATH%3D&type=code


我上午用你的固件测试更新完整固件时，界面显示lsblk缺失，中断了。然后我就刷了一个我op仓库的试了一下可以。

我还发现你的固件有个不同的地方是which总是会返回字符串，以如`which tar`返回`/bin/tar`，`which aaaaa`返回`/bin/……等path变量没有找到aaaaa`，一般来说没有时会返回空，所以 `[[ -n "$(which tar)" ]]` 检查返回值是否为空是可以的，但是你的固件的which检查没有的文件也总是返回非空的字符串，这个shell语法就不对了。不知道你用的这个分支的shell库还有哪些命令和常用的linux系统命令使用方法有差异。

另外就是为什么luci不能正常执行的sh文件，在终端下可以，可能imm新的javascript支持的luci-app-xxx标准下要声明什么？或者是你的固件里少个什么关键的软件包？

**Comment by etnperlong** [comment]
谢谢你的指点，对于 which 的问题，我特意测试了一下，可能刚好发现了问题所在

默认使用的 `which` 是 busybox 里面的 which，而我的固件里面的 which 则是 GNU Coreutils 版本的 which

输出的差别如下

GNU which

```
Usage: which [options] [--] COMMAND [...]
Write the full path of COMMAND(s) to standard output.

  --version, -[vV] Print version and exit successfully.
  --help,          Print this help and exit successfully.
  --skip-dot       Skip directories in PATH that start with a dot.
  --skip-tilde     Skip directories in PATH that start with a tilde.
  --show-dot       Don't expand a dot to current directory in output.
  --show-tilde     Output a tilde for HOME directory for non-root.
  --tty-only       Stop processing options on the right if not on tty.
  --all, -a        Print all matches in PATH, not just the first
  --read-alias, -i Read list of aliases from stdin.
  --skip-alias     Ignore option --read-alias; don't read stdin.
  --read-functions Read shell functions from stdin.
  --skip-functions Ignore option --read-functions; don't read stdin.

Recommended use is to write the output of (alias; declare -f) to standard
input, so that which can show aliases and shell functions. See which(1) for
examples.

If the options --read-alias and/or --read-functions are specified then the
output can be a full alias or function definition, optionally followed by
the full path of each command used inside of those.

Report bugs to <which-bugs@gnu.org>
```

Busybox 版本的 which

```
BusyBox v1.36.1 (2024-04-30 07:09:29 UTC) multi-call binary.

Usage: which [-a] COMMAND...

Locate COMMAND

        -a      Show all matches
```

我尝试修改 lua 的代码，将所有执行 `which` 的命令更换成 `busybox which` ，也可以在 LuCI 上执行更新了

在 Linux 的 [which 文档](https://linux.die.net/man/1/which) 中，可以看到默认行为是在 PATH 中搜索可执行命令，而 [busybox 的 which](https://boxmatrix.info/wiki/Property:which) 的路径是固定在 /usr/bin 和 /bin 下面

因此在没有环境变量的时候，busybox 的 which 依然能搜寻到这些依赖，造成了在我固件上面行为的差异

**Comment by etnperlong** [comment]
对于我的固件，我应该在构建的时候去除 which 这个依赖，让系统使用 busybox 的 which，即可解决这个问题
但为了更好的兼容性（可能也有部分固件使用了 coreutils ），我的建议是，可以在脚本上添加 PATH 变量引用，以及使用 `$?` 变量来判断 which 执行的返回值，而不是输出字符串，如果返回值大于0则表示依赖不存在
或者，显式指定使用 busybox which，也可以避免不同版本的 which 导致的行为差异
再次感谢你的帮助🙏

**Comment by ophub** [comment]
挺好，每消灭一个问题，就向完美又近了一步，感谢分享你的成果。
