### ISSUE TITLE
请问N1的这个版本可以使用晶晨宝盒升级 openwrt 吗？

### ISSUE THREAD

**Issue by wangjiegulu** [ophub/luci-app-amlogic#58]
19年的时候 N1 设备按照 right.com.cn 中的某个教程安装这个这个版本版本，后来一直没有升级过。
<img width="970" alt="image" src="https://github.com/user-attachments/assets/8d86c234-bb0b-45a3-8696-c17a1534c0aa">

安装的时候报这个错：
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/4dd3a3fe-13bc-42e1-b750-3756eb9b173f">

后台可以展示晶晨宝盒的页面，但是识别不出来 N1 的设备型号：
<img width="160" alt="image" src="https://github.com/user-attachments/assets/4177f89a-221f-4c16-a980-295456de8c8b">

按照这个 issue (<https://github.com/ophub/luci-app-amlogic/issues/21>) 手动添加了这个文件：

```
echo "PLATFORM='amlogic'" >/etc/flippy-openwrt-release
```

<img width="982" alt="image" src="https://github.com/user-attachments/assets/7dcd4ed8-a448-49ea-95d1-bbced7f98f7f">

想请问下目前可以使用晶晨宝盒安全升级吗？非常感谢解答！

**Comment by ophub** [comment]
可以，在线更新和手动上传更新均可。

**Comment by wangjiegulu** [comment]
> 可以，在线更新和手动上传更新均可。

非常感谢！

**Comment by wangjiegulu** [comment]
> 可以，在线更新和手动上传更新均可。
你好，在线更新报如下错：
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/a5058286-d428-4782-a4e8-15f3d9ba0c67">
