### ISSUE TITLE
error install in emmc

### ISSUE THREAD

**Issue by radityabh** [ophub/luci-app-amlogic#6]
![image](https://user-images.githubusercontent.com/15983827/129891497-63b1a632-0f21-424a-a7b3-6493893c0603.png)
i have this error when install to emmc, have any solution? thank you

**Comment by ophub** [comment]
- No need to change, click to install again.
https://github.com/ophub/luci-app-amlogic/blob/b43202fddec3b74fee38c8a9e00c11906a9506c4/luci-app-amlogic/root/usr/bin/openwrt-install#L396


- Where did you download the openwrt firmware and integrate the `fdisk` component when compiling?

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/4d73755ee34d4ba2cd31a7056486ea40f3a2067a/router-config/lede-master/.config#L562

**Comment by radityabh** [comment]
> * No need to change, click to install again.
>   https://github.com/ophub/luci-app-amlogic/blob/b43202fddec3b74fee38c8a9e00c11906a9506c4/luci-app-amlogic/root/usr/bin/openwrt-install#L396
> * Where did you download the openwrt firmware and integrate the `fdisk` component when compiling?
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/4d73755ee34d4ba2cd31a7056486ea40f3a2067a/router-config/lede-master/.config#L562

i fork your repo and compile it. yes i integrate the fdisk component.
![image](https://user-images.githubusercontent.com/15983827/130163247-825c33b1-e436-4545-ba84-6093a17d65a9.png)
i try several time, still error. i change the stb in x96max+ also the error apear.
![image](https://user-images.githubusercontent.com/15983827/130163487-179101d7-f8d5-4307-8dd1-dd9462be52d5.png)
this is my config
https://github.com/radityabh/amlogic-s9xxx-openwrt/blob/04092f04bd7bace3f8be3e8c2b992d520c63b599/router-config/lede-master/.config
