### ISSUE TITLE
N1 openwrt 21.02暂时不支持手动更新固件

### ISSUE THREAD

**Issue by ihuaer** [ophub/luci-app-amlogic#8]
![2021-11-20_121125](https://user-images.githubusercontent.com/12723080/142714044-d8ff7452-6939-4969-bae2-ed572e0e070d.png)
最近编译了openwrt 21.02 N1固件
测试在线更新固件，发现暂时无法更新，如图所示

**Comment by ophub** [comment]
This function comes from [luci-app-filetransfer](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-filetransfer), it is no problem under the source code of [lede](https://github.com/coolsnowwolf/lede) and [official](https://github.com/openwrt/openwrt), which `source code` did you use to compile it?

Openwrt test firmware compiled with lede's source code: [openwrt_lede](https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/openwrt_s9xxx_lede_2021.11.19.2343)

Openwrt test firmware compiled with official source code: [openwrt_official](https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/openwrt_s9xxx_official_2021.11.14.0106)

Did you time out, or the root user does not have a password? Set a new password, restart and test again.


![Snip20211120_2](https://user-images.githubusercontent.com/68696949/142719926-f1ad271b-8ef8-4b01-a888-56155b39a36b.png)

![Snip20211120_3](https://user-images.githubusercontent.com/68696949/142719931-b70fe7fd-3c60-4f7a-a03e-5aac342586a6.png)
