### ISSUE TITLE
安装 OpenWrt和手动上传更新疑问

### ISSUE THREAD

**Issue by Saxon-Sun** [ophub/luci-app-amlogic#9]
手动上传更新后会自动写入EMMC吗？还是需要在安装 OpenWrt的页面写入到EMMC

**Comment by ophub** [comment]
Uploading updates manually, updating online now, and updating the kernel all update the partition where the system you are currently operating on. If your current system is in the USB/TF, it will update the USB/TF, if it is in the EMMC, it will update the EMMC.

Click Install, then write from USB/TF to the EMMC partition that comes with the box.

Use on the USB/TF card, the function is exactly the same as that used in EMMC, you can choose which partition to use the OPENWRT system according to your preference.

**Comment by Saxon-Sun** [comment]
懂了 谢谢
